-- MySQL Script generated by MySQL Workbench
-- Thu Jul 16 17:17:24 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema proyecto_ney
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proyecto_ney
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecto_ney` DEFAULT CHARACTER SET utf8 ;
USE `proyecto_ney` ;

-- -----------------------------------------------------
-- Table `proyecto_ney`.`Account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_ney`.`Account` (
  `id_account` INT NOT NULL AUTO_INCREMENT,
  `name_account` VARCHAR(45) NULL,
  `amount_account` VARCHAR(45) NULL,
  PRIMARY KEY (`id_account`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_ney`.`Investment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_ney.`Investment` (
  `id_investment` INT NOT NULL AUTO_INCREMENT,
  `name_investment` VARCHAR(45) NULL,
  `amount_investment` VARCHAR(45) NULL,
  `income_investment` VARCHAR(45) NULL,
  PRIMARY KEY (`id_investment`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
